# postgres-openmetadata.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-openmetadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-openmetadata
  template:
    metadata:
      labels:
        app: postgres-openmetadata
    spec:
      containers:
        - name: postgres
          image: postgres:17.2-bookworm
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "openmetadata_db"
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: "512Mi"
              cpu: "0.2"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-openmetadata-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-openmetadata